@extends('errors.layout')
@section('code', '429')
@section('icon', 'fa-gauge-high')
@section('title', 'Un peu trop rapide !')
@section('message', "Vous avez effectué trop de requêtes en peu de temps. Patientez un instant avant de réessayer.")
